version: 2
jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-cache-{{ arch }}-{{ .Branch }}
            - npm-cache
      - run:
          name: install
          command: npm ci
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo/node_modules
      - run:
          name: build
          command: npm run build

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build-and-test
